/**
 * Style Dictionary build script — HabitaFactoría
 *
 * Usage:
 *   node build-tokens.mjs trust     → reads src/theme/theme-trust.json
 *   node build-tokens.mjs vibrant   → reads src/theme/theme-vibrant.json
 *
 * Generates: src/styles/tokens.css
 * 3-tier hierarchy: Base → Semantic → Component
 */

import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Resolve theme argument ──────────────────────────────────────────
const themeName = process.argv[2] || 'trust';
const themeFile = path.join(__dirname, 'src', 'theme', `theme-${themeName}.json`);

if (!fs.existsSync(themeFile)) {
  console.error(`❌ Theme file not found: ${themeFile}`);
  process.exit(1);
}

console.log(`🎨 Building tokens from: theme-${themeName}.json`);

// ── Read raw tokens for 3-tier generation ───────────────────────────
const rawTokens = JSON.parse(fs.readFileSync(themeFile, 'utf-8'));
const colors = rawTokens.color;
const spacing = rawTokens.spacing;
const borderRadius = rawTokens.borderRadius;
const shadows = rawTokens.shadow;

// ── Build 3-tier CSS variable map ───────────────────────────────────
// Tier 1: Base — raw values from JSON
// Tier 2: Semantic — meaningful aliases
// Tier 3: Component — component-specific variables

const cssVariables = [];

// ── COLORS ──────────────────────────────────────────────────────────
const primaryHex = colors.primary.$value;
const accentHex = colors.accent.$value;

// Tier 1 — Base
cssVariables.push(`/* ═══ Base Tokens ═══ */`);
cssVariables.push(`--color-blue-600: ${primaryHex};`);
cssVariables.push(`--color-white: ${accentHex};`);

// Tier 2 — Semantic
cssVariables.push(``);
cssVariables.push(`/* ═══ Semantic Tokens ═══ */`);
cssVariables.push(`--color-primary: var(--color-blue-600);`);
cssVariables.push(`--color-accent: var(--color-white);`);
cssVariables.push(`--color-text-on-primary: var(--color-white);`);
cssVariables.push(`--color-text-body: #1a1a1a;`);
cssVariables.push(`--color-text-muted: #6b7280;`);
cssVariables.push(`--color-bg-body: #f9fafb;`);
cssVariables.push(`--color-bg-surface: var(--color-white);`);
cssVariables.push(`--color-border: #e5e7eb;`);

// Tier 3 — Component
cssVariables.push(``);
cssVariables.push(`/* ═══ Component Tokens ═══ */`);
cssVariables.push(`--button-bg: var(--color-primary);`);
cssVariables.push(`--button-text: var(--color-text-on-primary);`);
cssVariables.push(`--button-radius: var(--radius-md);`);
cssVariables.push(`--card-bg: var(--color-bg-surface);`);
cssVariables.push(`--card-border: var(--color-border);`);
cssVariables.push(`--card-radius: var(--radius-lg);`);
cssVariables.push(`--header-bg: var(--color-primary);`);
cssVariables.push(`--header-text: var(--color-accent);`);
cssVariables.push(`--footer-bg: #1f2937;`);
cssVariables.push(`--footer-text: #d1d5db;`);

// ── SPACING ─────────────────────────────────────────────────────────
cssVariables.push(``);
cssVariables.push(`/* ═══ Spacing ═══ */`);
for (const [key, val] of Object.entries(spacing)) {
  if (key.startsWith('$')) continue;
  cssVariables.push(`--spacing-${key}: ${val.$value};`);
}

// ── BORDER RADIUS ───────────────────────────────────────────────────
cssVariables.push(``);
cssVariables.push(`/* ═══ Border Radius ═══ */`);
for (const [key, val] of Object.entries(borderRadius)) {
  if (key.startsWith('$')) continue;
  cssVariables.push(`--radius-${key}: ${val.$value};`);
}

// ── SHADOWS ─────────────────────────────────────────────────────────
cssVariables.push(``);
cssVariables.push(`/* ═══ Shadows ═══ */`);
for (const [key, val] of Object.entries(shadows)) {
  if (key.startsWith('$')) continue;
  const s = val.$value;
  cssVariables.push(
    `--shadow-${key}: ${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color};`
  );
}

// ── Write tokens.css ────────────────────────────────────────────────
const outputDir = path.join(__dirname, 'src', 'styles');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const cssContent = `/* ═══════════════════════════════════════════════
   Design Tokens — Theme: ${themeName.charAt(0).toUpperCase() + themeName.slice(1)}
   Auto-generated by Style Dictionary
   Source: src/theme/theme-${themeName}.json
   ═══════════════════════════════════════════════ */

:root {
${cssVariables.map(v => `  ${v}`).join('\n')}
}
`;

const outputPath = path.join(outputDir, 'tokens.css');
fs.writeFileSync(outputPath, cssContent, 'utf-8');

console.log(`✅ Generated: src/styles/tokens.css (${themeName} theme)`);